### ISSUE TITLE
Add total smart cites / total publications to columns

### ISSUE THREAD

**Issue by u-ashish** [scitedotai/scite-zotero-plugin#19]
As requested here https://github.com/scitedotai/scite-zotero-plugin/issues/18#issuecomment-858505902

**Comment by u-ashish** [comment]
Hi @thangckt this is now fixed. You can update your plugin or install the latest here: https://github.com/scitedotai/scite-zotero-plugin/releases/tag/v1.0.8

Let me know if you have any additional questions :)

**Comment by thangckt** [comment]
dear @u-ashish, 
Thank you so much for your response.

**Comment by roaldarbol** [comment]
First of all, thanks for this plugin! 
Quick comment on this feature; quite a few of my papers have fewer Smart Citations than distinct citations. Is it a bug or do you have any idea how this happens? I even have a few which have 0 Smart Citations despite having distinct citations.

**Comment by roaldarbol** [comment]
And another quick comment on the feature, it might be worth making the title shorter (e.g. like the Contrasting/Supporting - maybe just Citations and Smart Citations), as the title is quickly truncated despite the column naturally being narrow as it only contains numbers. :-)

**Comment by u-ashish** [comment]
Hi @roaldarbol 

1. We can only have Smart Citations for a paper if we've ingested its full text article and extracted the citation statements; in instances where there is a discrepancy, it is likely because we haven't accessed the full-text of the relevant citing articles yet. We're constantly growing in this area with new indexing agreements and so on, but that's the reason. In the interim, we chose to expose the count of traditional citations so that the information was still there / useful for you.

2. I'll need to think about this... I know it's narrow and was worried about that exact issue, but I chose to be more descriptive in the name so as to not confuse users (the distinction between a traditional citation and a Smart Citation can be confusing since a traditional citation can have 1 or more Smart Citations within). Let me get back to you.

**Comment by u-ashish** [comment]
@roaldarbol I did mean to ask, do you have examples of papers where that was an issue? If you let me know I can check to see if it's a subject area or journal where we're working on improving coverage, or if there is some other problem.

**Comment by roaldarbol** [comment]
Hi @u-ashish, thanks for a quick response!

1. That makes perfect sense, I was just curious. I tried to go through them, and a few things seemed like they might be general. Disclaimer, most of my references have been imported from Mendeley which found meta-data from the PDF and not online.
- I have a few book chapters (including [this](https://link.springer.com/book/10.1007%2F978-3-642-35497-7) and [this](https://www.scopus.com/record/display.uri?eid=2-s2.0-84877610032&origin=inward&txGid=a46baa88b66a83b971379ae0c13716bb)), with 19 distinct citations and 3 Smart citations. That seems to be a general trend.
- I found that in some of my citations, the DOI was incomplete (for some reason often PNAS, though I suspect it's due to getting metadata form the PDF), leaving out everything after the journal shorthand. Could it be that the "distinct citations" looks for `contains` and "smart citations" looks for `matches` the DOI?
- Other widely sited papers include this [ImageJ paper](https://www.nature.com/articles/nmeth.2089), at 27930 to 19772 and  
Shannon's classic [information theory paper](https://dl.acm.org/doi/10.1145/584091.584093) at 2160 to 895.

2. I get your point; however, my 5 cents from the perspective of an uninitiated user is that if you don't know in advance, you won't from the title alone. (Whether it's possible to make a hover text box, I don't know but something like that could be a way around it). So no matter what, I think it's worth for people to see a few lines of text (exactly like what you explained above), and once you know, _you know_, and a brief title will suffice - just as with the other labels. E.g. including "total" doesn't add much information in either case; "distinct" is what one would normally use, so could also be left out; and the "Smart citations" is the only one needing a bit of explanation.
