### ISSUE TITLE
Zotero 7.0 Support

### ISSUE THREAD

**Issue by johntian** [scitedotai/scite-zotero-plugin#55]
Zotero [announced](https://forums.zotero.org/discussion/105094/announcing-the-zotero-7-beta) the **[7.0 beta](https://www.zotero.org/support/dev/zotero_7_for_developers)** version 3 months ago. Please update this plugin accordingly. Thx!

**Comment by u-ashish** [comment]
Hey @johntian thanks for opening this issue. I'm a little swamped but will have a look in the coming week or two on the release plan and what changes are required here to support this.

**Comment by VectorZhao** [comment]
+1

**Comment by fishgirl7** [comment]
ahh sorry - I just opened a new issue with this exact issue. v7.0.0 broke EVERYTHING :(

**Comment by u-ashish** [comment]
Yeah, we don't support 7 yet, sorry. I started looking into this last week but still trying to find time for it. I'll give you all a clearer update middle of next week at least on what you can expect (it's mostly just me right now).

**Comment by 11good11** [comment]
> Yeah, we don't support 7 yet, sorry. I started looking into this last week but still trying to find time for it. I'll give you all a clearer update middle of next week at least on what you can expect (we're both spread thin so I'm sorry to keep you all waiting).

I have been waittig for you, 3q U

**Comment by u-ashish** [comment]
Okay, so I started looking at this then stopped for a while because of other things that came up on our end. We're spread a little thin and I know it's frustrating!

I'm planning to get back to you all by early next week on a timeline of what you can expect. I guess this would also be a good time to see if anyone has any interest in contributing to this project and helping out if they're interested (with my supervision), but regardless, will get back in a bit. Thanks again for your patience and sorry I've just been a little swamped.

**Comment by 11good11** [comment]
> Okay, so I started looking at this then stopped for a while because of other things that came up on our end. We're spread a little thin and I know it's frustrating!
> 
> I'm planning to get back to you all by early next week on a timeline of what you can expect. I guess this would also be a good time to see if anyone has any interest in contributing to this project and helping out if they're interested (with my supervision), but regardless, will get back in a bit. Thanks again for your patience and sorry I've just been a little swamped.

我们从未离去，一直在等待等待，我不知道能帮助些什么，如果需要对插件bug进行测试，我愿意代劳，可以直接讲预制好的程序发到评论下就好，我会根据使用情况进行反馈

**Comment by woodae99** [comment]
> Okay, so I started looking at this then stopped for a while because of other things that came up on our end. We're spread a little thin and I know it's frustrating!
> 
> I'm planning to get back to you all by early next week on a timeline of what you can expect. I guess this would also be a good time to see if anyone has any interest in contributing to this project and helping out if they're interested (with my supervision), but regardless, will get back in a bit. Thanks again for your patience and sorry I've just been a little swamped.


Thanks u-ashish, one more eager member of the crowd waiting for Z-7 support. While I'm here, any chance of getting Scite collections to sync with Zotero like ResearchRabbit does?

**Comment by u-ashish** [comment]
@woodae99  -- I think a better sync would be nice. For now, we made it so that if you use the zotero browser extension, it should be able to pick up the DOIs on the page. Depending on the dashboard size this can do the trick, but I know that it's not the best workflow yet.

Sorry for all the hold up... this has clearly been on my list but we're a small team and sort of drowning in things so it's been hard to chip away. If anyone's interested in contributing, drop me a note here or at ashish@scite.ai to see if we can work something out. Otherwise, sorry to make you all wait :(

**Comment by woodae99** [comment]
@u-ashish -- thanks for taking the time to engage, I can imagine that you and the team must be pulled in all directions right now. If I knew how to code, I'd be on this like white on rice to try and help :)

And just because I haven't asked enough of you yet... when you do get around to making updates, will you also add to the Zotero feature-set, links from the Scite stats columns in the main Zotero library window, or the Scite details tab, so that a click opens the paper in Scite?

**Comment by 11good11** [comment]
> @woodae99 -- I think a better sync would be nice. For now, we made it so that if you use the zotero browser extension, it should be able to pick up the DOIs on the page. Depending on the dashboard size this can do the trick, but I know that it's not the best workflow yet.——我想更好的同步会很好。现在，我们这样做是为了如果你使用zotero浏览器扩展，它应该能够在页面上获取doi。根据仪表板的大小，这可以做到这一点，但我知道这还不是最好的工作流程。
> 
> Sorry for all the hold up... this has clearly been on my list but we're a small team and sort of drowning in things so it's been hard to chip away. If anyone's interested in contributing, drop me a note here or at [ashish@scite.ai](mailto:ashish@scite.ai) to see if we can work something out. Otherwise, sorry to make you all wait :(抱歉耽搁了这么久...这显然已经在我的清单上了，但我们是一个小团队，有点淹没在事情中，所以很难一点一点地离开。如果有人有兴趣投稿，请在这里或ashish@scite.ai给我留言，看看我们是否能解决一些问题。否则，很抱歉让你们都等了：（。

我们一直在等待，从来不会放弃，我时常回来看看，因为我支持你们，并永远相信你们会回来！

**Comment by carllx** [comment]
Okay, I'm also waiting for the update. Let's stay tuned together!

**Comment by giuliogcantone** [comment]
Should we re-install the scite add-on for Z7?

**Comment by aadjiet** [comment]
Hi, 
I know you guys are very busy and have other more important issues to look at, however, I have waited for this update for quite a long time, to use scite, I will downgrade as I cannot wait for this anymore. 
Hope to see the update soon:)

**Comment by carllx** [comment]
+1

**Comment by linem7** [comment]
+1

**Comment by rbvk** [comment]
Eager about the release of scite support for Zotero 7

**Comment by secondbrain-note** [comment]
I am subscribed to scite and longing for the scite support for zotero 7.

**Comment by symonef** [comment]
Hi there, just checking in on the progress of this? I subscribe to Scite and would love to use the plugin on Zotero 7

**Comment by Walkwise-0** [comment]
Following and interested. Just bought a Scite annual subscription and would be very cool to have this plugin for Zotero 7.0 :)

**Comment by aadjiet** [comment]
Hi,

 I Upgraded my Zotero to 6.0.37 and its working fine.

regards,
Allie

**Comment by u-ashish** [comment]
Hi everyone- I know you're all waiting and I wanted to at least comment and say that I'm not ignoring these messages.

We've been swamped with the acquisition and prioritizing work and a lot of focus has been on the main product itself. It helps to see folks writing in and voicing their feedback here though; I'm doing what I can to get some attention on this project.

If I can't find someone internally to prioritize this, I'll start chipping away at this in mid-May once I wrap up a few other things and get back from an upcoming work trip. Really hate to make you all wait this long.

**Comment by narath** [comment]
Hey @u-ashish, appreciate the info about all the competing priorities. Just checking in to see if there was an ETA on this. I think this addition is *so* important to the science community.

**Comment by u-ashish** [comment]
> Hey @u-ashish, appreciate the info about all the competing priorities. Just checking in to see if there was an ETA on this. I think this addition is _so_ important to the science community.

Oops, I forgot to write, I started chipping away last weekend. I'll try to give a more substantial update soon.

**Comment by awsamuel** [comment]
I'm so glad to hear you're working on this! The ability to see citation count directly in Zotero is one of the primary features that keeps me on scite rather than genei, consensus or some other research platform. Really look forward to having the plugin back.

**Comment by u-ashish** [comment]
I made a little progress 😅 A lot changed... Hoping to test it out by next weekend

**Comment by 11good11** [comment]
> I made a little progress 😅 A lot changed and am trying to make it work on both to avoid having two separate builds... Hoping to test it out by next weekend. If it's a pain I'll just create a new release / branch that isn't backwards compatible since our plugin is pretty simple anyway我取得了一点进步，😅改变了很多，我正试图让它在两者上工作，以避免有两个独立的构建...希望在下周末之前测试一下。如果这很痛苦，我会创建一个不向后兼容的新版本/分支，因为我们的插件非常简单

明日复明日，明日何其多，我生待明日，万事成蹉跎！

**Comment by sascharo** [comment]
> Should we re-install the scite add-on for Z7?

I don't think that will work; it doesn't for me.

**Comment by sascharo** [comment]
> I made a little progress 😅 A lot changed and am trying to make it work on both to avoid having two separate builds... Hoping to test it out by next weekend. If it's a pain I'll just create a new release / branch that isn't backwards compatible since our plugin is pretty simple anyway

Great to know it's coming.

**Comment by TomYU2023** [comment]
When will your team update the plugin for zo7？very expect

**Comment by TomYU2023** [comment]
When will your team update the plugin for zo7？ It almost has gone  for 1 year， very expect

**Comment by JiahaoWen93** [comment]
Hey I'm here to check how this issue going.

**Comment by sascharo** [comment]
In the meantime, I switched to Zotero 6...

**Comment by songcolin** [comment]
It's been a year since this thread got started, Zotero released 7.0 already and still nothing from scite. This demonstrates the sheer incompetence in software development.

**Comment by u-ashish** [comment]
> It's been a year since this thread got started, Zotero released 7.0 already and still nothing from scite. This demonstrates the sheer incompetence in software development.

Hey- 

Believe me I know this should not take this long. Since a lot of folks are watching I can shed a little bit of light on why this is dragging out (but I have been making good progress, I just need to figure out a few things on the deployment side).

We've historically been a small team. When I joined 4 years ago, the total engineering / product headcount was 3. As of last June, it was 2 (including me). If you've used scite, you can guess how complex it is internally.

This issue started last August when we were going through our acquisition which closed in December 2023, so we were pretty heads down on M&A as well as a bunch of other product and engineering work on the main platform.

Of course after the acquisition the focus was continuing that and quite a bit more work on integrations with our parent company. As you can imagine, our team was spread pretty thin the entire time and I just had to prioritize our efforts elsewhere.

I hate to keep you all waiting this long and honestly it is embarrassing something this simple couldn't have been done sooner, but it's not because of competence, just a constant bandwidth issue.

With that said, I think I have it working locally with Z7, but I was trying to figure out the deployment side, so I'm not ignoring this!

**Comment by e-kotov** [comment]
@u-ashish such a polite response to such a rude comment above...

Sad to see people leaving mean comments with little to no understanding of how software development even works and what kind of circumstances can slow down the process.

@u-ashish thanks for the great work!

**Comment by u-ashish** [comment]
I need to clean this up and will bug one of you to test but should be ready in a day or two. I'll most likely release this as a new major version and remove some of the legacy code; it's a bit tricky to make it backwards compatible and while I can put the effort in, it's going to make the code harder to read. Anyone sticking with Zotero 6 can always install the older version of the plugin.

<img width="1176" alt="Screen Shot 2024-08-12 at 1 28 53 PM" src="https://github.com/user-attachments/assets/84075582-0fe6-4bb2-8aa6-abacb38abf58">

**Comment by u-ashish** [comment]
Hi all- many thanks for your patience. 

The latest release has support for Zotero 7. You can find it here: https://github.com/scitedotai/scite-zotero-plugin/releases/tag/v2.0.1 -- please note that it is not backwards compatible, so if you are on Zotero 6 you will need to use an older version.

I don't know if the auto-update will work if you had the older version installed, but if not, please disable the old and re-install the XPI file from above.

As a tiny note, tomorrow is actually my last day at scite / Research Solutions; I've got some other things planned for the future. It's bittersweet but I really wanted to get this out before I left.

I'm happy to be available here and will help maintain the plugin as new issues arise to the extent that I can, since this plugin is public. But if anyone's interested in contributing, drop me a note at ashish.uppala.93@gmail.com and I can help you ramp up. My time will be a little more free for now so hopefully no more one-year long waits 🤗 .

Let me know if you run into issues with this release by opening a new issue and we can go from there.

Cheers,
Ashish

**Comment by woodae99** [comment]
Thanks for everything, Ashish. All the best for the new chapter!

**Comment by erikseidenfaden** [comment]
Thank you for being so helpful with updating the Scite plugin for Zotero!

I have installed the new version of Zotero and the updated plugin for Scite. (Scite 2.0.1).

However, the citations that were shown (i guess correctly) in the older version of Zotero do not work correctly in Zotero 7.0

I attach an example here:
<img width="1709" alt="Screenshot 2024-08-21 at 13 29 43" src="https://github.com/user-attachments/assets/2855a2cf-ecb4-4660-860d-eebef4816ced">
<img width="1538" alt="Screenshot 2024-08-21 at 13 32 03" src="https://github.com/user-attachments/assets/f1436191-c637-4ae9-8046-5a1b6c2a4ab4">

Best regards, 
Erik

**Comment by sascharo** [comment]
> I have installed the new version of Zotero and the updated plugin for Scite. (Scite 2.0.1).
> 
> However, the citations that were shown (I guess correctly) in the older version of Zotero do not work correctly in Zotero 7.0

Is this working for you now?

**Comment by JacobKorir** [comment]
I downloaded the Scite plugin (V2.0.2) using Chrome and I'm using Zotero 7.0.11. The plugin is installed but it is not working. Has anyone found a solution?
